apiVersion: monitoring/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
  serviceAccountName: prometheus
  securityContext:
    fsGroup: 2000
  ruleSelector:
    matchLabels:
      role: prometheus
      prometheus: k8s
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-main
      port: web
