apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: k8s
spec:
  replicas: 3
  serviceAccountName: prometheus
  securityContext:
    fsGroup: 2000
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
      - namespace: default
        name: alertmanager-main
        port: web
  ruleSelector:
    matchLabels:
      role: prometheus
      prometheus: k8s
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
  version: 2.30.3  # Set the Prometheus Operator version that matches your setup
