name: Build, Push, Run, Check, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest

  run-and-check:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull Docker Image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
        
    - name: Check if Container is Running
      run: |
        while true; do
          if curl -s http://localhost:80; then
            echo "Container is up and running."
            break
          else
            echo "Waiting for the container to start..."
            sleep 5
          fi
        done

    - name: Tag Docker Image for Google Cloud Artifact Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKERHUB_REPO }}:latest

    - name: Push Docker Image to Google Cloud Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKERHUB_REPO }}:latest

  deploy:
    needs: run-and-check
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials tamir-cluster --region me-west1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Create GKE Cluster
      run: |
        gcloud container clusters create tamir-cluster --region=me-west1 --num-nodes=3 --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE Cluster
      run: |
        kubectl run your-app-deployment --image=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest --port=80 --generator=run-pod/v1
        kubectl expose deployment your-app-deployment --type=LoadBalancer --port 80 --target-port 80
